### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jasonkuhrt**
Elasticsearch is not a camel-cased name.

### CODE REVIEW

**Comment by jasonkuhrt** [comment]
Whoops I need to update this with some changes to other files too. Pending...

**Comment by jasonkuhrt** [comment]
Ok, good to go now!

**Comment by pilwon** [comment]
@jasonkuhrt Great catch. Thanks-.

**Comment by jasonkuhrt** [comment]
@pilwon Cheers.

**Pull request merged**
